# Generated by Django 4.1.6 on 2023-02-14 10:45

import common.fields.lower_case_char_field
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDeviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('shaft', 'Shaft system'), ('hole', 'Hole system')], max_length=5, verbose_name='System')),
                ('base_deviation', models.CharField(choices=[('es', 'Upper deviation'), ('ei', 'Lower deviation')], max_length=2, verbose_name='Base deviation')),
                ('designation', common.fields.lower_case_char_field.LowerCaseCharField(max_length=2, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z][a-zA-Z]?$')], verbose_name='Designation')),
            ],
            options={
                'unique_together': {('system', 'designation')},
            },
        ),
        migrations.CreateModel(
            name='GradeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_over', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Over')),
                ('range_up_to', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Up to')),
            ],
            options={
                'unique_together': {('range_over', 'range_up_to')},
            },
        ),
        migrations.CreateModel(
            name='BaseDeviationGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_um', models.IntegerField()),
                ('base_deviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deviations.basedeviation', verbose_name='Base deviation')),
                ('range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deviations.graderange', verbose_name='Grade range')),
            ],
            options={
                'unique_together': {('range', 'base_deviation')},
            },
        ),
    ]
