# Generated by Django 4.1.6 on 2023-02-14 11:49

import common.fields.lower_case_char_field
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deviations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basedeviation',
            options={'verbose_name': 'Основное отклонение', 'verbose_name_plural': 'Base deviations'},
        ),
        migrations.AlterModelOptions(
            name='basedeviationgrade',
            options={'verbose_name': 'Base deviation grade', 'verbose_name_plural': 'Base deviation grades'},
        ),
        migrations.AlterModelOptions(
            name='graderange',
            options={'verbose_name': 'Диапазон', 'verbose_name_plural': 'Диапазоны'},
        ),
        migrations.AlterField(
            model_name='basedeviation',
            name='base_deviation',
            field=models.CharField(choices=[('es', 'Верхнее отклонение'), ('ei', 'Нижнее отклонение')], max_length=2, verbose_name='Основное отклонение'),
        ),
        migrations.AlterField(
            model_name='basedeviation',
            name='designation',
            field=common.fields.lower_case_char_field.LowerCaseCharField(max_length=2, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z][a-zA-Z]?$')], verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='basedeviation',
            name='system',
            field=models.CharField(choices=[('shaft', 'Система вала'), ('hole', 'Система отверстия')], max_length=5, verbose_name='Система'),
        ),
        migrations.AlterField(
            model_name='basedeviationgrade',
            name='base_deviation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deviations.basedeviation', verbose_name='Основное отклонение'),
        ),
        migrations.AlterField(
            model_name='basedeviationgrade',
            name='range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deviations.graderange', verbose_name='Диаппазон'),
        ),
        migrations.AlterField(
            model_name='graderange',
            name='range_over',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Свыше'),
        ),
        migrations.AlterField(
            model_name='graderange',
            name='range_up_to',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='До'),
        ),
    ]
